
name: 'Red Hat Helm Chart Certifier'
description: ''
inputs:
  chart_uri:
    description: URI to Helm Chart to verify. This can be a path to the chart directory, or an http(s) URI.
    required: true
  report_type:
    description: '{all,annotations,digests,metadata,results}'
    required: true
    default: results
  # config_file_path:
  #   description: Path to chart-verifier configuration file
  #   required: false
  verify_args:
    description: Extra arguments to pass to the 'verify' command.
    required: false
# outputs:

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CHART_URI: ${{ inputs.chart_uri }}
    REPORT_TYPE: ${{ inputs.report_type }}
    # CONFIG_FILE_LOCATION: ${{ inputs.config_file_path }}
  args:
    - ${{ inputs.verify_args }}
