name: Chart Verifier

on:
  push:
  workflow_dispatch:


jobs:
  chart-verifier:
    name: Chart Verifier
    runs-on: ubuntu-20.04
    steps:
      - name: login
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      - run: echo $KUBECONFIG

      - uses: ./
        with:
          chart_uri: https://redhat-actions.github.io/openshift-actions-runner-chart
