name: Chart Verifier

on:
  push:
  workflow_dispatch:


jobs:
  chart-verifier:
    name: Chart Verifier
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: Print Kube context info
        run: |
          echo $KUBECONFIG

      - uses: ./
        name: Verify Chart
        id: verify
        with:
          chart_uri: https://github.com/redhat-actions/openshift-actions-runner-chart/blob/release-chart/packages/actions-runner-1.1.tgz?raw=true
          verify_args: --chart-set githubOwner=tetchel
          fail: false

      - name: Echo outputs
        run: echo "${{ toJSON(steps.verify.outputs) }}"

      - uses: ./
        name: Verify Chart with different profile
        id: verify-2
        with:
          chart_uri: https://github.com/redhat-actions/openshift-actions-runner-chart/blob/release-chart/packages/actions-runner-1.1.tgz?raw=true
          verify_args: --chart-set githubOwner=tetchel
          profile_name: "community"
          profile_version: "1.1"
          fail: false

      - name: Echo outputs again
        run: echo "${{ toJSON(steps.verify-2.outputs) }}"
