name: Chart Verifier

on:
  push:
  workflow_dispatch:


jobs:
  chart-verifier:
    name: Chart Verifier
    runs-on: ubuntu-20.04
    steps:
      - uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      - run: echo $KUBECONFIG

      - uses: actions/checkout@v2
        with:
          path: chart-verifier-action

      - uses: actions/checkout@v2
        with:
          repository: redhat-actions/openshift-actions-runner-chart
          path: runner-chart
          ref: main

      - run: |
          ls
          ls runner-chart
          ls chart-verifier-action

      - uses: ./chart-verifier-action
        with:
          chart_uri: ./runner-chart
          verify_args: --set githubOwner=tetchel
